digit_30: 30
digit_65: 65
digit_4: 4
digit_3: 3
digit_5: 5
digit_6: 6
digit_1: 1
star_range: 1..5
confirmed_status: "confirmed"
cancelled_status: "cancelled"
remember_me_checked: "1"
dd_mm_yyyy: "%d-%m-%Y"
datime_format: "%d-%m-%Y %H:%M:%S"
datime_format_hour: "%d-%m-%Y %H"
default_number_of_guests: 1
min_number_of_guests: 1
max_number_of_guests: 100
digit_0: 0
images_limit: 6
img_tag_size: "150x150"
height_img_250: 250
width_img_250: 250
img_format: "image/jpeg,image/gif,image/png"
VALID_EMAIL_REGEX: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
VALID_PHONE_REGEX: "\\A\\+?[\\d\\s\\-\\(\\)]+\\z"
ADMIN: 1
USER: 0
user:
  min_len_email: 6
  max_len_email: 50
  min_len_phone: 8
  max_len_phone: 50
  max_len_address: 255
  max_len_first_name: 50
  max_len_last_name: 50
  min_len_password: 6
flight:
tour:
  max_len_name: 100
  max_duration: 30
  limit_250_250: [250, 250]
  items_per_page: 10
  rev_tours_per_page: 5
  search:
    min_duration: 1
    max_duration: 30
    min_price: 0
    max_price: 99999
    start_date: "2000-01-01"
review:
  max_rating: 5
  min_rating: 1
booking:
  min_guests: 0
  min_price: 0
  items_per_page: 5
  search:
    min_guests: 1
    min_total_price: 0
    min_started_date: "2000-01-01"
voucher:
  items_per_page: 10
  search:
    percent_discount: 0
    min_total_price: 0
